--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/HighestDreams/Form
build-by-default: true
branches:
- main
projects:
  tests.WelcomeUI:
    path: tests/WelcomeUI/
  Form:
    path: ""
    model: virion
    type: library
...
